name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13.3
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'
          cache: 'pip'
          cache-dependency-path: 'setup.py'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          pip install flake8 black isort mypy pytest-cov

      - name: Cache linting results
        uses: actions/cache@v4
        with:
          path: |
            .mypy_cache
            .pytest_cache
            .black_cache
          key: ${{ runner.os }}-lint-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-lint-

      - name: Run Flake8
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --output-file=flake8-results.txt

      - name: Run Black
        run: black . --check --verbose

      - name: Run isort
        run: isort . --check-only --verbose

      - name: Run MyPy
        run: mypy . --cache-dir .mypy_cache

      - name: Run tests with coverage
        run: |
          pytest --cov=. --cov-report=xml --cov-report=term-missing

      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-results
          path: |
            coverage.xml
            flake8-results.txt
          retention-days: 7

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: true 