name: Test Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          
      - name: Set up test environment
        run: |
          # Create test directories
          mkdir -p input output
          # Copy example config file to input directory
          cp transaction_config.example.json input/transaction_config.json
          # Install reportlab for PDF generation
          pip install reportlab
          # Create a simple PDF for testing
          python3 -c "
          from reportlab.pdfgen import canvas
          from reportlab.lib.pagesizes import letter
          c = canvas.Canvas('input/sample.pdf', pagesize=letter)
          c.drawString(100, 750, 'Sample Credit Card Statement')
          c.save()
          "
          
      - name: Run tests with coverage
        run: |
          pytest --cov=./ --cov-report=xml
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: codecov-umbrella
          verbose: true
          
      - name: Cleanup
        if: always()
        run: |
          rm -rf input output 