name: Docker Build and Test

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'compose.yaml'
      - 'requirements.txt'
      - 'ccs_extract.py'
      - '.github/workflows/docker.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'compose.yaml'
      - 'requirements.txt'
      - 'ccs_extract.py'
      - '.github/workflows/docker.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ccs-extract:latest

      - name: Create test environment
        run: |
          mkdir -p input output
          # Set directory permissions to 755 (owner: rwx, group: rx, others: rx)
          chmod 755 input output
          # Set ownership to current user
          chown -R $USER:$USER input output
          cp transaction_config.example.json transaction_config.json
          # Create a simple PDF for testing using Python
          python3 -c "
          from reportlab.pdfgen import canvas
          from reportlab.lib.pagesizes import letter
          c = canvas.Canvas('input/sample.pdf', pagesize=letter)
          c.drawString(100, 750, 'Sample Credit Card Statement')
          c.save()
          "

      - name: Run Docker Compose tests
        run: |
          # Test basic container functionality
          docker run --rm -v $(pwd)/input:/app/input:ro -v $(pwd)/output:/app/output:rw ccs-extract:latest /app/input/sample.pdf --output /app/output/sample.csv
          
          # Check if output file was created
          if [ ! -f "output/sample.csv" ]; then
            echo "Error: Output file was not created"
            exit 1
          fi
          
          # Check if output file has the correct headers
          if ! grep -q "Transaction Date,Merchant,Category,Transaction Details,Amount" output/sample.csv; then
            echo "Error: Output file does not contain expected headers"
            exit 1
          fi

      - name: Cleanup
        if: always()
        run: |
          rm -rf input output 